--Create  table 'LABEL'

CREATE TABLE label (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp DEFAULT now() NOT NULL,
	CONSTRAINT label_name_key UNIQUE (name),
	CONSTRAINT label_pkey PRIMARY KEY (id)
);

--Create  table 'TASK'

CREATE TABLE task (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(255) NULL,
	status int2 NULL,
	title varchar(255) NULL,
    created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp DEFAULT now() NOT NULL,
	CONSTRAINT task_pkey PRIMARY KEY (id),
	CONSTRAINT task_status_check CHECK (((status >= 0) AND (status <= 3)))
);

--Create  table 'TASK_LABEL'
CREATE TABLE task_label (
	task_id int4 NOT NULL,
	label_id int4 NOT NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp DEFAULT now() NOT NULL,
	CONSTRAINT task_label_pkey PRIMARY KEY (task_id, label_id)
);